name: e2e
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  packages: read
  contents: read

jobs:
  call-e2e-test-workflow:
    uses: ./.github/workflows/e2e_reusable.yaml